### ISSUE TITLE
editor-style.css もゴシック体になってほしいです

### ISSUE THREAD

**Issue by mayukojpn** [hinaloe/Nippombashi-2016#4]

**Comment by hinaloe** [comment]
準備中です！

**Comment by hinaloe** [comment]
@mayukojpn #5 をクローン(checkout)して動作確認してもらえると嬉しいです:)

**Comment by mayukojpn** [comment]
はや！お仕事おわったら試してみます、ありがとうございます！（やってなかったらつついてください.....!）

**Comment by hinaloe** [comment]
CSSは先に用意してたのでそれを読み込むコードだけ書けてなかったとですw()

**Comment by hinaloe** [comment]
@mayukojpn ping
